### ISSUE TITLE
Snap and Wine icon apps not shown

### ISSUE THREAD

**Issue by mvidaldp** [nsz32/docklike-plugin#13]
Snap and Wine app icons are not shown. In case of Wine, the default/standard Wine icon is shown instead. In case of snaps, there's no icon.
Could you fix that or it has nothing to do with docklike?

![image](https://user-images.githubusercontent.com/19171462/80015752-7ccc8c00-84d2-11ea-8a44-50320f89b491.png)

**Comment by nsz32** [comment]
I will probably work on wine app icons soon.

Was your snap apps just been installed ? -> There was a bug about newly installed apps (no icon) that was solved with my new commit.
If not, can you tell me the path of the .desktop file of one of your snap application ?

Ty

**Comment by mvidaldp** [comment]
Hi, I updated to the newest version of docklike. The app icons aren't shown. The snaps weren't just installed.

The path of my snaps .desktop is next:
~/.local/share/applications/*.desktop -> /var/lib/snapd/desktop/applications/*.desktop
Example for Spotify:
~/.local/share/applications/spotify_spotify.desktop -> /var/lib/snapd/desktop/applications/spotify_spotify.desktop

Thanks to you for helping and developing such a great dockbar for the xfce panel.

**Comment by nsz32** [comment]
Symlinks !

**Comment by mvidaldp** [comment]
All snap apps show properly, also the icons appear in the default xfce panel taskbar. But not in yours.

Example:

X-SnapInstanceName=spotify
Type=Application
Name=Spotify
GenericName=Music Player
Icon=/var/lib/snapd/snap/spotify/41/usr/share/spotify/icons/spotify-linux-128.png
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/spotify_spotify.desktop /var/lib/snapd/snap/bin/spotify %U
Terminal=false
MimeType=x-scheme-handler/spotify;
Categories=Audio;Music;Player;AudioVideo;
StartupWMClass=spotify

Do you think the symlinks are a problem? I actually created them manually to try to make the icons appear on your dock.

**Comment by nsz32** [comment]
My bad, I was asking if every snap application don't show properly ...
Ty for the content, i will investigate.

**Comment by mvidaldp** [comment]
I'm not sure if I got you well. But all snap apps show properly but for their missing icons on your dock bar.

Thanks for helping!

**Comment by nsz32** [comment]
I installed snap, then spotify and ghex (a simple software) with it. None of them simply starts (insolvable dependency pb (!?) and segfault). I would have tried further if I haven't found this "package manager" so ... opaque (to be VERY gentle). So short answer : don't use snap !

Long answer, questions:
- When you said `/usr/share/applications/spotify_spotify.desktop -> /var/lib/snapd/desktop/applications/spotify_spotify.desktop`, did you mean that there is a symlink (->) between these to path ?

- Can you check the results of `echo $XDG_DATA_DIRS`, this variable should contains paths to /applications/ folders containing .desktop files (or .desktop symlinks to these). For example it should contains /usr/share/. With these paths (+ /applications/), can you reach your spotify_spotify.desktop file ? This is how the plugin find them.

- Update docklike, then run `xfce4-panel -q; PANEL_DEBUG=1 xfce4-panel&` in a terminal. This will restart the panel in debug mode. You should be able to get some informations when a new window show up. Example:
`SEARCHING GROUPNAME:file-roller
> APPINFO NAME:Archive Manager
> APPINFO PATH:/usr/share/applications/org.gnome.FileRoller.desktop
> APPINFO ICON:org.gnome.ArchiveManager`
Give me these 4 lines for some snap apps.

- What is your distro ?

ty

**Comment by mvidaldp** [comment]
> I installed snap, then spotify and ghex (a simple software) with it. None of them simply starts (unsolvable dependency pb (!?) and segfault). I would have tried further if I haven't found this "package manager" so ... opaque (to be VERY gentle). So short answer : don't use snap !
> 
I wish I could just easily install every software I need from my package manager without problems. But unfortunately, it's not always the case. Almost 100% of the packages I use are from pacman (including AUR), but I found out that for a very few it's quite convenient to use flatpak or snap. I use it for Spotify, Slack, Adobe Acrobat Reader, uTorrent and Standard Notes. Basically, software that is not (yet) well implemented or stable in Linux, or just not implemented at all. And using Wine sometimes requires lots of testing and research, so snap and flatpak do the job for you.
![image](https://user-images.githubusercontent.com/19171462/80294234-8cb0ce00-8767-11ea-951e-99923127fb08.png)

> Long answer, questions:
> 
>     * When you said `/usr/share/applications/spotify_spotify.desktop -> /var/lib/snapd/desktop/applications/spotify_spotify.desktop`, did you mean that there is a symlink (->) between these two path ?
Yes, so I manually created the symlinks to /usr/share/applications and ~/.local/share/applications since in some forums they suggested it as a solution. Unfortunately, it didn't work for me.
> 
>     * Can you check the results of `echo $XDG_DATA_DIRS`, this variable should contains paths to /applications/ folders containing .desktop files (or .desktop symlinks to these). For example it should contains /usr/share/. With these paths (+ /applications/), can you reach your spotify_spotify.desktop file ? This is how the plugin find them.
As you can see, /usr/share is there, and /var/lib/snapd/desktop as well:
![image](https://user-images.githubusercontent.com/19171462/80294481-802d7500-8769-11ea-9cdb-0098f953247d.png)

> 
>     * Update docklike, then run `xfce4-panel -q; PANEL_DEBUG=1 xfce4-panel&` in a terminal. This will restart the panel in debug mode. You should be able to get some informations when a new window show up. Example:
>       `SEARCHING GROUPNAME:file-roller`
>       `> APPINFO NAME:Archive Manager`
>       `> APPINFO PATH:/usr/share/applications/org.gnome.FileRoller.desktop`
>       `> APPINFO ICON:org.gnome.ArchiveManager`
>       Give me these 4 lines for some snap apps.
> 
>     * What is your distro ?
> 
> 
> ty

I'll check it out and I'll come back to you. My distro is Manjaro.

Thanks a lot again for all this effort and help.

**Comment by mvidaldp** [comment]
I don't get exactly the lines you're asking for so I'll attach a screenshot. I hope it helps.

![image](https://user-images.githubusercontent.com/19171462/80294607-e961b800-876a-11ea-95a0-52461630a775.png)

**Comment by nsz32** [comment]
Ok, .desktop files usually give icon by its name. Snap apps .desktop give icon by a path.
Fixed. You can rebuild your plugin ;)

I could have saved time to you and me by closely look at the files provided by snap ...

`Wine case will demand more hard work.`

**Comment by mvidaldp** [comment]
It's not completely solved. Now the icons take the size of the original icon resolution.

![image](https://user-images.githubusercontent.com/19171462/80295656-da800300-8774-11ea-8c17-57cba9e38f3f.png)

![image](https://user-images.githubusercontent.com/19171462/80295693-28950680-8775-11ea-9d04-6bed139a795a.png)


I could create smaller copies of the icons to solve it now, but. Could you add a general fix?

**Comment by nsz32** [comment]
Working on it already ;)

**Comment by nsz32** [comment]
This is done :)

**Comment by mvidaldp** [comment]
Thank you very very very much!! It works like a charm now :)

**Comment by mvidaldp** [comment]
By the way, I also noticed the mini icons from the window app information while mouse hovering the icons are not always there.
In this case this is not a snap nor wine exclusive issue. Do you need any extra information from xfce4-panel in debug mode to check that?

**Comment by nsz32** [comment]
Are you talking about the mini icons in windows list ?
Best is a "step to reproduce" : Give me the smallest application which will bug in that way.
